### PR TITLE
Removed dependency on the mailgun api

### LINKED ISSUE #71: Mailgun Dependency Issue
We should not be dependent on the mailgun api. The process must continue if mailgun is not working or is throwing errors at us. Right now, it is impossible to create a group if mailgun is not working or has changed their api.

1. group creation should have the option to not create a mail list
2. existing group without a mailing list should be allowed to create a list
3. if mailgun is down or throws an error, we should still proceed with creating the group or any other group request. This is not the case right now.

### PR DESCRIPTION
**Pull request by igaponov**
Resolved #71

### CODE REVIEW

File: backend/src/Civix/FrontBundle/Controller/Group/MemberController.php [hunk 1]
```diff
@@ -66,20 +69,14 @@ public function memberRemoveAction(User $user)
...
-
-            $groupName = $slugify->slugify($this->getUser()->getOfficialName(), '');
-
-            $mailgun = $this->get('civix_core.mailgun')->listremovememberAction($groupName, $this->getUser()->getEmail());
-
-            if ($mailgun['http_response_code'] != 200) {
+            try {
+                $this->get('civix_core.group_manager')
+                    ->unjoinGroup($user, $this->getUser());
+            } catch (MailgunException $e) {
```
Comment (austinpapp) [inline backend/src/Civix/FrontBundle/Controller/Group/MemberController.php]: :+1:
