### PR TITLE
Fix event listeners

### LINKED ISSUE #89: Argument 3 passed to Civix\CoreBundle\Service\Group\GroupManager::__construct() ...
Look this [constructor](https://github.com/PowerlineApp/powerline-server/blob/develop/backend/src/Civix/CoreBundle/Service/Group/GroupManager.php#L44), the constructor has 3 parameters but the [container resource](https://github.com/PowerlineApp/powerline-server/blob/develop/backend/src/Civix/CoreBundle/Resources/config/services.xml#L173) just have 2 params. I believe this will thow an exception. So I think it better to test your changes before create pull request.

### LINKED ISSUE #90: PHP Fatal error:  Cannot use Civix\CoreBundle\Entity\Micropetitions\Petition
Not sure if you @all have the same behaviour as mine. but I got this error message when run `PowerlineApp/powerline-server` `develop` branch.

    PHP Fatal error:  Cannot use Civix\CoreBundle\Entity\Micropetitions\Petition as Petition because the name is already in use in /vagrant/backend/src/Civix/CoreBundle/Entity/Activities/MicroPetition.php on line 6

### PR DESCRIPTION
**Pull request by igaponov**
Resolves #89 
Resolves #90

### CODE REVIEW

File: backend/src/Civix/CoreBundle/Tests/Entity/Activities/MicroPetitionTest.php [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+use Civix\CoreBundle\Entity\Activities\Petition;
+use Civix\CoreBundle\Entity\Micropetitions\Metadata;
+
+class MicroPetitionTest extends \PHPUnit_Framework_TestCase
+{
+    public function testPetitionClassNameConflict()
+    {
+        new Petition(); // conflict between Activities\Petition and Micropetitions\Petition
+        $microPetition = new MicroPetition();
+        $petition = new \Civix\CoreBundle\Entity\Micropetitions\Petition();
```
Comment (shakaran) [inline backend/src/Civix/CoreBundle/Tests/Entity/Activities/MicroPetitionTest.php]: Probably it is better write as new Petition() and move above the use Civix\CoreBundle\Entity\Micropetitions\Petition, because when we write more test in this class or others will decrease readability in my opinion and write more when we can use the "imports" (use) for classes. If conflicts like now, you can use "as" keyword for conflict naming and put other names for example (suggested):

    use Civix\CoreBundle\Entity\Activities\Petition as CoreActivityPetition;
    use Civix\CoreBundle\Entity\Micropetitions\Petition as CoreMicroPetition;
    use Civix\CoreBundle\Entity\Activities\MicroPetition as ActivityMicroPetition;

Comment (austinpapp) [inline backend/src/Civix/CoreBundle/Tests/Entity/Activities/MicroPetitionTest.php]: the above is just a suggestion on readability, correct @shakaran? At some point, we should look at the structure of these classes and maybe attempt to clean up some legacy problems. This comes back to the ubiquitous language issue we seem to suffer from.

Comment (shakaran) [inline backend/src/Civix/CoreBundle/Tests/Entity/Activities/MicroPetitionTest.php]: @austinpapp yes, it is only a suggestion about readability (and future code maintenability). It will works perfectly like is written now, just trying to give my 2 cents in the peer review

Comment (austinpapp) [inline backend/src/Civix/CoreBundle/Tests/Entity/Activities/MicroPetitionTest.php]: @shakaran comments on code _exactly_ what i want us to be doing. so thank you.
